import 'package:flutter/material.dart';
import 'package:iconsax/iconsax.dart';
import 'package:rice_yield_app/core/utils/app_colors.dart';
import 'package:rice_yield_app/features/auth/presentation/widgets/auth_back_button.dart';
import '/core/theme/theme.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  static const _sections = [
    (
      'Information we collect',
      'We collect account details (name, email), uploaded field videos, and '
          'analysis results generated by our AI yield model. This data is used '
          'only to provide and improve the Rice Yield App service.',
    ),
    (
      'How we use your data',
      'Your videos and reports are processed to estimate rice yield metrics. '
          'We do not sell personal data to third parties. Aggregated, anonymized '
          'statistics may be used to improve model accuracy.',
    ),
    (
      'Data storage & security',
      'Data is stored on secure cloud infrastructure with access limited to '
          'authenticated users. We apply industry-standard safeguards; no '
          'method of transmission over the internet is 100% secure.',
    ),
    (
      'Your rights',
      'You may request access, correction, or deletion of your account data by '
          'contacting support. You can sign out at any time from the Profile screen.',
    ),
    (
      'Updates to this policy',
      'We may update this privacy policy from time to time. Continued use of the '
          'app after changes constitutes acceptance of the revised policy.',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: SafeArea(
        child: CustomScrollView(
          slivers: [
            SliverPadding(
              padding: const EdgeInsets.fromLTRB(12, 8, 20, 0),
              sliver: SliverToBoxAdapter(
                child: Row(
                  children: [
                    const AuthBackButton(),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        'Privacy Policy',
                        style: AppTheme.headlineLarge.copyWith(
                          fontSize: 24,
                          color: AppColors.primary,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            SliverPadding(
              padding: const EdgeInsets.fromLTRB(20, 16, 20, 28),
              sliver: SliverList(
                delegate: SliverChildListDelegate([
                  _InfoBanner(
                    icon: Iconsax.shield_tick,
                    text:
                        'Last updated: May 2026. This policy describes how Rice Yield App handles your information.',
                  ),
                  const SizedBox(height: 20),
                  ..._sections.map(
                    (s) => Padding(
                      padding: const EdgeInsets.only(bottom: 12),
                      child: _PolicySection(title: s.$1, body: s.$2),
                    ),
                  ),
                ]),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _InfoBanner extends StatelessWidget {
  const _InfoBanner({required this.icon, required this.text});

  final IconData icon;
  final String text;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppColors.primary.withValues(alpha: 0.1)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: AppColors.primary,
              borderRadius: BorderRadius.circular(10),
            ),
            child: Icon(icon, color: Colors.white, size: 18),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              text,
              style: AppTheme.bodyMedium.copyWith(
                fontSize: 12,
                color: Colors.grey.shade600,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _PolicySection extends StatelessWidget {
  const _PolicySection({required this.title, required this.body});

  final String title;
  final String body;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 12,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: AppTheme.bodyLarge.copyWith(
              fontWeight: FontWeight.w600,
              color: AppColors.primary,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            body,
            style: AppTheme.bodyMedium.copyWith(
              color: Colors.grey.shade600,
              height: 1.45,
            ),
          ),
        ],
      ),
    );
  }
}
